### ISSUE TITLE
About point cloud encoder

### ISSUE THREAD

**Issue by filaPro** [buaacyw/MeshAnything#12]
Hi, @buaacyw 

Thanks for sharing your wonderful research. Just small question. Do I understand correctly, that you use point cloud encoder frozen with exactly the same weights, provided by Michelangelo paper? So this part of the model is trained only on ShapeNet, not ShapeNet + Objavarse?

**Comment by buaacyw** [comment]
Hi, thanks a lot for your interest in our work! We used exactly the same weights from its [github repo](https://github.com/NeuralCarver/Michelangelo). Different from its paper, the encoder-decoder released by Michelangelo in its repo is in fact trained on Objaverse + ShapeNet.

**Comment by filaPro** [comment]
Got it, thanks.
May I ask how did you know that they trained on Objaverse + ShapeNet?)

**Comment by buaacyw** [comment]
Aha, I asked the first author of Michelangelo about this.
