### ISSUE TITLE
Point Clouds

### ISSUE THREAD

**Issue by adrsch** [buaacyw/MeshAnything#7]
Hey, I see the picture of point clouds being used as an input. How do I do this?

**Comment by buaacyw** [comment]
Please refer to the USAGE section of README.

**Comment by adrsch** [comment]
Thanks, I see it now!

**Comment by adrsch** [comment]
Oh, okay, I closed that too quickly. I see it only supports npy files. I am having trouble finding a tool that will let me convert to that. I've got my point clouds in polycam so I can export ply, las, pts, syz, and dxf.

Correct me if I'm wrong but I don't think metashape supports npy either - is this meant to be used with actual scans?

**Comment by adrsch** [comment]
Yeah I get it now this software isn't meant for real world use.
