### ISSUE TITLE
Poor results using mesh input files

### ISSUE THREAD

**Issue by adrsch** [buaacyw/MeshAnything#8]
This is a photogrammetry scan of a little pouch, processed as a mesh. Once I can get the point cloud converted to npy I'll try that method as well. Potential issue is holes. Is a sealed mesh required for good results? Here's what I've been getting. 
Without a polygon limit, it just gave me the input mesh but maybe half the polygons optimized away. It was still an extremely high poly mesh. I want something useable. 

Here's the 250 max triangle limit run. The little bunch of polygons toward the bottom. Looks nothing like the input mesh. 

python main.py --input_dir ..\props\magnifyingglass\bag\obj --out_dir ..\props\magnifyingglass\bag --input_type mesh --n_max_triangles 250

Look at this output! Utterly awful! I've got to be doing something wrong if you are capable of getting the results in your photos.

![Screenshot 2024-06-20 211354](https://github.com/buaacyw/MeshAnything/assets/35346279/75d31d42-3511-4bc8-bd77-ff97a3b89e55)
![Screenshot 2024-06-20 211358](https://github.com/buaacyw/MeshAnything/assets/35346279/784a7db0-0e7e-4000-ab80-627cf136f309)

**Comment by adrsch** [comment]
I get it, marking this closed, the software isn't ready for real world usage yet.

**Comment by yosun** [comment]
this is disappointing that it's not an open feature request. 

you may want to add to readme the small subset of low poly meshes that this works with?
